

















// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "Web.config"
//     Connection String Name: "SiteSqlServer"
//     Connection String:      "Data Source=disgrafic-vm02\sql2016;Initial Catalog=Somatracking;User ID=dnn;password=**zapped**;"
// ------------------------------------------------------------------------------------------------

// -----------------------------------------------------------------------------------------
// Failed to read database schema in LoadTables() - Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=6172; handshake=1155; 
// -----------------------------------------------------------------------------------------


// -----------------------------------------------------------------------------------------
// Failed to read database schema for stored procedures - Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=6172; handshake=1155; 
// -----------------------------------------------------------------------------------------

